### ISSUE TITLE
Proposal: use the Java bindings for the Kabanero CRDs

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-landing#118]
#### Feature description
There are generated Java wrappers around the operator CRDs that are published to Maven Central. We should consider using these when we read the Kabanero CR instances from Kubernetes using the Jave kube client.

#### Feature design or visual mockup
There are no visual elements to this feature.

#### Additional context
This branch shows how one would convert the command line services to use the Java mappings (I've converted all of the existing code).
https://github.com/kabanero-io/kabanero-command-line-services/compare/master...kaczyns:kabaneroMappings?expand=1

To import the mappings, include the following in the pom.xml:
```xml
    <dependency>
      <groupId>io.kabanero</groupId>
      <artifactId>operator-java-bindings</artifactId>
      <version>0.0.1</version>
    </dependency>
```

**Comment by alohr51** [comment]
@kSee04 could you see if this can be helpful to us currently, and if not, maybe it would fit into some future plans of using this.

**Comment by kSee04** [comment]
@alohr51 Here's source for reference https://github.com/kabanero-io/operator-java-bindings/. We've already written similar Java code for doing operations on Kab Instances/Collections, but we should definitely leverage these Java mappings instead. I'll work on getting this imported to the landing page.

**Comment by kSee04** [comment]
@kaczyns What's the maintenance plan for the `operator-java-bindings` repo? Who owns driving issues/updates on this repo? Would that be you?

**Comment by kaczyns** [comment]
@kSee04 Yes, I plan to update that repo when we make changes to the CRDs.  I'm assuming that I'll do this once per release of Kabanero.
