### ISSUE TITLE
Kabanero 0.5-rc2 NPE when accessing collections after setting up Oauth

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-landing#132]
Running Kabanero 0.5-rc2 build. I setup Oauth to use github.ibm.com as Oauth source.
After setting up for the landing page to use Oauth , the manage collections button showed up in the
Instances page under collections.

Issue originator: Shelton Skinner

PRs:
    https://github.com/kabanero-io/kabanero-landing/pull/130
    https://github.com/kabanero-io/kabanero-landing/pull/131

**Comment by marikaj123** [comment]
It is verified by the SVT team. closed.

**Comment by csskinner25** [comment]
Checked with 0.5.0-rc3. This is now fixed
