### ISSUE TITLE
GM version of landing page still says 0.5..0-rc.2

### ISSUE THREAD

**Issue by csskinner25** [kabanero-io/kabanero-landing#145]
Installed GM version of kabanero

curl -s -O -L https://github.com/kabanero-io/kabanero-operator/releases/download/0.5.0/install.sh

After install the kabanero landing page has 0.5.0-rc.2 at the bottom.

![image](https://user-images.githubusercontent.com/53049234/73465679-b7e57600-434e-11ea-9496-68ce30dda902.png)

Should be 0.5.0

**Comment by alohr51** [comment]
thanks for the heads up @csskinner25 !

**Comment by alohr51** [comment]
Image version was fixed. Same image tag: `kabanero/landing:0.5.0`
