### ISSUE TITLE
Broken Installing Codewind in Codeready Workspaces link in Set Up Dev Tools

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-landing#237]
#### Describe the bug
- Use Kabanero 0.9.0-rc.1
- From Kabanero Landing home page, click on `Set Up Dev Tools`.
- Click on link `Installing Codewind in Codeready Workspaces`, I got `The requested page does not exist.`  
The url it directs to is https://kabanero-landing-kabanero.apps.<_host_>/docs/ref/general/installation/installing-codeready-and-codewind

#### Expected behavior

Link should point to the correct page to install codeready

#### Actual behavior

Link is broken

#### Steps to reproduce the bug
See defect description

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

#### Screenshots
- click on the following link:
   <img width="468" alt="Screen Shot 2020-05-05 at 3 20 11 PM" src="https://user-images.githubusercontent.com/22480038/81113586-1be77f80-8ee6-11ea-8e40-602b30db4dd9.png">
 
- Got this page
   <img width="1002" alt="Screen Shot 2020-05-05 at 3 36 18 PM" src="https://user-images.githubusercontent.com/22480038/81113643-31f54000-8ee6-11ea-8aae-1f0b9f7c306e.png">

**Comment by kidus60** [comment]
bug was fixed in pr - https://github.com/kabanero-io/kabanero-landing/pull/234/files#diff-7983241e3e8e3c4abe51016bf92f5d6eR118
