### ISSUE TITLE
Suppress warning messages on governance for invalid stacks

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-landing#241]
#### Describe the bug

Originally from @mtamboli 
https://github.com/kabanero-io/kabanero-operator/issues/700

After enabling OAuth for landing page, I see that governance policy is displayed. But it is showing below warning about active stacks which does not relevant to me and taking too much attention of the user. Talked to @dacleyra and he thinks that operator might be able suppress them.

![image](https://user-images.githubusercontent.com/29490950/81429772-4c205f80-912c-11ea-8b31-f2a26e572365.png)

Probably need to check active/inactive before performing digest check. An inactive Stack does not have a Status with asset digests.

#### Steps to reproduce the bug
3. Scroll to '....'

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

**Comment by alohr51** [comment]
@stephenkinder @mdenby @davco01a Any thoughts on whether to show or not show the digest warning when a stack is _inactive_.

My thoughts:

**Keep showing the warning on inactive status** - I think its nice to know there _will_ be a warning if you do decide to activate the stack.

**Do not show the warning on inactive status** - Will not distract the user from thinking there is a problem, cleaner UI, but will show up the second they activate the stack which may be a surprise. This also means they won't know there is a digest issue until they already activated the stack.

**Comment by mtamboli** [comment]
> @stephenkinder @mdenby @davco01a Any thoughts on whether to show or not show the digest warning when a stack is _inactive_.
> 
> My thoughts:
> 
> **Keep showing the warning on inactive status** - I think its nice to know there _will_ be a warning if you do decide to activate the stack.
> 
> **Do not show the warning on inactive status** - Will not distract the user from thinking there is a problem, cleaner UI, but will show up the second they activate the stack which may be a surprise. This also means they won't know there is a digest issue until they already activated the stack.

@alohr51 Why would the warning be there when you activate? warning was not there when stacks were active. Warning happening when the stack is deactivated.

**Comment by davco01a** [comment]
The digest metadata is unavailable in the Stack CR when it’s inactive

**Comment by mdenby** [comment]
If the stack is in use, then show the warning. But if it's not being used--for either/or builds and deploys--don't show it.

**Comment by stephenkinder** [comment]
@alohr51 @davco01a Since the Stack CR holds the digest at the time of activation, the digest value is undefined if it is inactive.  When you active the stack, the digest will be set -- so no error will result when the stack is reactivated, the digest is set to the new value.

**Comment by davco01a** [comment]
+1 @stephenkinder
