### ISSUE TITLE
Authentication / Authorization decision for user experience

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-landing#65]
#### Feature description

we need to decide on how authorization happens in the user experience flow of things.

#### Feature design or visual mockup

some ideas:

1. Use OAuth with the OKD console
   * A possible back draw is we still need GitHub access for CLI server auth, so they would need to login twice here

2. Use GitHub OAuth
   * All auth roles would need to be handled in GitHub which is a little weird

3. A mixture of both 1 and 2
   * Users would have to login twice once to OKD console and once to GitHub.

**Comment by stephenkinder** [comment]
@alohr51 the CLI team and Security team can help you consider their approaches so that we have a synergistic approach across the components.

**Comment by alohr51** [comment]
some thoughts after a call with Jim last week

1. Normal OAuth with the OCP console.
   * Pro - Can do this
   * Con - Do not get any GitHub info or able to send any GitHub REST requests for the user.

1. OCP Console & Kabanero Console are both configured to have GitHub as OAuth Provider
   * Pros
      - Can do this today
      - Can configure console app to use GitHub OAuth directly as well
      - Can get GitHub teams and make REST requests for the user.
   * Cons
      - OCP cannot pass the GitHub OAuth token back
      - The Kabanero console does not go through the OCP Console for OAuth
      - Any additional OAuth Providers would have to be coded into the Kabanero Console
      - OCP Console and Kabanero Console can get out of sync with their OAuth Provider if one is updated and the other isn't.

1. OCP Console is configured to use GitHub as an OAuth provider and can pass both tokens back
   * Pros
      - Kabanero Console uses the OCP consoles OAuth
      - We can make GitHub REST requests for the user
   * Cons
      - Not implemented yet.

**Comment by alohr51** [comment]
Right now I don't think there is a "unified" OAuth for Kabanero, what I mean by this is, we don't **require** GitHub OAuth (or any other OAuth provider) to be setup on OKD/OC.
  * this means I am leaning towards doing number 2 from the list above where the OKD/OCP GitHub OAuth and the Kabanero console GitHub OAuth are both **optional**.

This way, the Kabanero console will be the way it is today with the **added optional support** of logging into the configured GitHub when the Kab Instance was created.

We won't have to rely on having the users setup OAuth themselves, we will just support it if there is a configured GitHub.

**Comment by alohr51** [comment]
This is what I am envisioning for the instance page. So there wouldn't be an entire console application lockdown on logging into GitHub, only this specific tile inside the console app and the new collection page with collection management functions

![image](https://user-images.githubusercontent.com/3623618/70075450-d89d8380-15ca-11ea-823c-9728a6239939.png)

**Comment by alohr51** [comment]
@ralanlittle @jtmulvey @cajaygle any opinions on this method (last 3 comments above)? If doesn't have to be the final method, but it seems like a good starting point.

**Comment by alohr51** [comment]
Going to go with the implementation in this comment to start: https://github.com/kabanero-io/kabanero-landing/issues/65#issuecomment-561260628

**Comment by jtmulvey** [comment]
@alohr51 I agree with this initial approach to not yet integrate with OpenShift's OAuth server for this and instead drive the login to Git using the Kab CLI Login microservice and subsequent microservices to do CRUD ops on collections.  The JWT will work the same for this as it does for the Kab CLI we have today that runs as a Go app on the client.  This means when this is driven from the OCP console, where the user has already logged in, they will need to click the Login with Github button and login again.  This is fine for now- and maybe forever for such a use case.  Adding @chunlongliang-ibm as an FYI.

**Comment by alohr51** [comment]
@kaczyns created some lovely diagrams of proposed changes for this work.

[kabanero_github_oauth.pdf](https://github.com/kabanero-io/kabanero-landing/files/3956878/kabanero_github_oauth.pdf)

**Comment by chunlongliang-ibm** [comment]
@kaczyns , about your comment "userApi and website don’t appear to be important?" Those 3 github configuration properties are useful:
userNameAttribute="login" userApi="https://api.github.com/user" scope="user repo read:org" .
Both "userNameAttribute" and "scope" can be fixed (hardcoded).  The "userApi" should be configurable
