### ISSUE TITLE
watch for events instead of refreshing every 5 min

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-landing#69]
#### Feature description

Currently we refresh the instance data every 5 minutes. We should be setting up event watchers to watch for data changes as they happen.

#### Feature design or visual mockup

Example of watching using the io.kubernetes java client https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

**Comment by marikaj123** [comment]
@kidus60 - Is the issue ready to close.

**Comment by kidus60** [comment]
@marikaj123 the issue is still in progress

**Comment by marikaj123** [comment]
@kidus60 - Is the issue ready to close?

**Comment by alohr51** [comment]
We'll be switching to use the Kabanero bindings library to get info for the kabanero CRD - so this issue will be replaced with that work. #129
