### ISSUE TITLE
CodeReady is not mentioned in landing page "Set Up Dev Tools" topic

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-landing#81]
#### Describe the bug
CodeReady is not mentioned in the Set Up Dev tools topic accessible from the Kabanero landing page

#### Expected behavior
CodeReady is a dev tool that has been added, so when clicking on the `Set Up Dev Tools` option on the Kabanero landing page, the expectation is that there would be some mention of CodeReady and a point to installing it.

#### Actual behavior
The page currently only mentions Codewind and Appsody CLI

#### Steps to reproduce the bug
1. Go to 'Kabanero Landing Page'
2. Click on 'Set Up Dev Tools' under `Let's get started` heading
3. See the issue

#### Environment where the bug occurred 
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)

#### Screenshots

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/31766760/69269191-81e18400-0b9e-11ea-850b-aae6abe6bc54.png">

**Comment by alohr51** [comment]
currently blocked by kabanero-io/docs/issues/118

**Comment by alohr51** [comment]
@mdenby you mentioned you would like to design a spot for CodeReady on the setup dev tools, this is the issue you can put your design in when you have it, thanks!

**Comment by mdenby** [comment]
Let's just add "If using CodeReady IDE" with "Install CodeReady from Red Hat Developer" as the link to https://developers.redhat.com/products/codeready-workspaces/overview

This should be below Eclipse. Definitely let me know if that link is the correct one.

**Comment by alohr51** [comment]
@mdenby that's def the correct product, but I just realized the Kabanero Operator will actually do the install for you so maybe we should link to https://github.com/kabanero-io/docs/blob/master/ref/general/installation/installing-codeready-and-codewind.adoc (but the actual doc in the application not GitHub)

**Comment by mdenby** [comment]
@alohr51 That's even better that we'll do the install for them! Let's use that link.
